### ISSUE TITLE
Include PurgeCSS to remove unecessary selectors in the output CSS file

### ISSUE THREAD

**Issue by RighteousHundred** [kevin-powell/demo-starter-template-with-sass#1]
Hi @kevin-powell!

I have a little performance tip for this template repository that could remove all of the unnecessary classes in the CSS output. 
The output CSS file becomes _really_ big because all of the color utility classes are there. If you included **[PurgeCSS](https://github.com/FullHuman/purgecss#packages)**, it would listen to an HTML file, and only include the CSS _that you use_ in the output. 
Heads up: Tailwind CSS v3.0 uses PurgeCSS to remove all the unnecessary classes in their output CSS file.

Please consider doing this for performance or discuss a little bit about this minification strategy.

EvanWebDev

**Comment by kevin-powell** [comment]
Because off how I'm using this, I don't have the need. Nothing will be going into production, it's only just for when I'm creating new YouTube demos. But yes, I would use purgeCSS on a production site for sure 👍
