### ISSUE TITLE
The premium Alaska font is available for anyone to download for free!

### ISSUE THREAD

**Issue by RighteousHundred** [kevin-powell/demo-starter-template-with-sass#2]
Hi @kevin-powell!

When I go into the fonts folder, I see a file called alaska.tff.
You bought this font. And, it's available for anyone who is on this repository for free. Shouldn't this be unaccessible for people who don't pay for the font, @kevin-powell?

EvanWebDev

**Comment by RighteousHundred** [comment]
I Googled it and the Alaska font is free to download for anyone, so this issue is incorrect!

EDIT: Only the non-variable font is available for free to download. You need to pay for the variable font, and anyone can access it for free in this repository!

**Comment by RighteousHundred** [comment]
Actually, the regular Alaska font can be downloaded for free. However, for the variable font, you have to pay! And on this repository, the font is available to anyone to download for free!

**Comment by kevin-powell** [comment]
Thanks for pointing that out, will be fixing that now 👍
